# Generated by Django 4.0.2 on 2022-04-05 14:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_alter_question_db_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField()),
                ('start_time', models.DateTimeField(default=datetime.datetime(2022, 4, 5, 20, 7, 51, 135276))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2022, 4, 5, 20, 7, 51, 135276))),
                ('professor', models.ForeignKey(limit_choices_to={'groups__name': 'PROFESSOR'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='questions.question_paper')),
            ],
        ),
    ]
