# Generated by Django 4.0.2 on 2022-04-06 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_exam_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam_model',
            options={'verbose_name_plural': 'Exams'},
        ),
        migrations.AddField(
            model_name='question_paper',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 20, 39, 11, 580924)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 20, 39, 11, 580924)),
        ),
    ]
