# Generated by Django 4.0.2 on 2022-04-06 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_exam_model_options_question_paper_marks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam_model',
            old_name='total_marks',
            new_name='marks',
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 21, 6, 33, 44435)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 6, 21, 6, 33, 44435)),
        ),
    ]
