# Generated by Django 4.0.2 on 2022-04-07 06:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_rename_total_marks_exam_model_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_Question',
            fields=[
                ('question_db_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.question_db')),
                ('choice', models.CharField(default='E', max_length=3)),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('questions.question_db',),
        ),
        migrations.AlterModelOptions(
            name='question_paper',
            options={'verbose_name_plural': 'Question Papers'},
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 12, 6, 48, 52955)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 7, 12, 6, 48, 52955)),
        ),
        migrations.CreateModel(
            name='StuExam_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('completed', models.IntegerField(default=0)),
                ('qpaper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question_paper')),
                ('questions', models.ManyToManyField(to='questions.Stu_Question')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
