# Generated by Django 4.0.3 on 2022-04-20 05:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0007_alter_exam_model_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sturesults_db',
            options={'verbose_name_plural': 'Student Results'},
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 11, 26, 56, 805362)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 11, 26, 56, 805362)),
        ),
        migrations.AlterField(
            model_name='stu_question',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stuexam_db',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sturesults_db',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'STUDENT'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
