# Generated by Django 4.0.2 on 2022-03-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
